### ISSUE TITLE
JSX compiling error `Unexpected token <`

### ISSUE THREAD

**Issue by evgenosiptsov** [halt-hammerzeit/webpack-isomorphic-tools#107]
Thanks a lot for great tool! 

But i don't can integrate webpack-isomorphic-tools in existing react-project

```
[root@ns project]# node ./server/index.js
[webpack-isomorphic-tools] [debug] instantiated webpack-isomorphic-tools v2.5.8 with options {
  "debug": true,
  "assets": {
    "images": {
      "extensions": [
        "png",
        "jpg",
        "jpeg",
        "gif",
        "ico",
        "svg"
      ]
    }
  },
  "webpack_assets_file_path": "webpack-assets.json",
  "webpack_stats_file_path": "webpack-stats.json"
}
[webpack-isomorphic-tools] [debug] entering production mode
[webpack-isomorphic-tools] [debug] registering require() hooks for assets
[webpack-isomorphic-tools] [debug]  registering a require() hook for *.png
[require-hacker] [debug] Hooking into *.png files loading
[webpack-isomorphic-tools] [debug]  registering a require() hook for *.jpg
[require-hacker] [debug] Hooking into *.jpg files loading
[webpack-isomorphic-tools] [debug]  registering a require() hook for *.jpeg
[require-hacker] [debug] Hooking into *.jpeg files loading
[webpack-isomorphic-tools] [debug]  registering a require() hook for *.gif
[require-hacker] [debug] Hooking into *.gif files loading
[webpack-isomorphic-tools] [debug]  registering a require() hook for *.ico
[require-hacker] [debug] Hooking into *.ico files loading
[webpack-isomorphic-tools] [debug]  registering a require() hook for *.svg
[require-hacker] [debug] Hooking into *.svg files loading
[require-hacker] [debug] Hooking into *.webpack-loaders files loading
/home/project/node_modules/react-ux-password-field/src/index.js:229
      infoBar = (<div className="passwordField__info" style={this.infoStyle}>
                 ^

SyntaxError: Unexpected token <
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Module._extensions..js (module.js:422:10)
    at Object.require.extensions.(anonymous function) [as .js] (/home/project/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/home/project/app/assets/js/components/input-password.js:3:21)
    at Module._compile (module.js:413:34)
```

I do not understand why webpack-isomorphic-tools trying to compile JSX without react-babel transfromations.

**Comment by evgenosiptsov** [comment]
my server/index.js:
```
require('babel-register');

// Adds common/js to the app module path so we can access local modules without
// having to use relative paths on the server-side. This is done on the client
// side using webpack's `resolve`.
require('app-module-path').addPath('common/js');

// css-modules-require-hook package allows us to require css files on the server.
require('css-modules-require-hook')({
  extensions: ['.scss'],
  generateScopedName: require('../package.json').config.css,
  devMode: process.env.NODE_ENV === 'development'
});

// this must be equal to the Webpack configuration's "context" parameter
const basePath = require('path').resolve(__dirname, '..');
const ISOTools = require('webpack-isomorphic-tools');


global.__CLIENT__ = false;
global.__SERVER__ = true;
global.__DISABLE_SSR__ = false;  // <----- DISABLES SERVER SIDE RENDERING FOR ERROR DEBUGGING
global.__DEVELOPMENT__ = process.env.NODE_ENV !== 'production';


// this global variable will be used later in express middleware
global.ISOTools = new ISOTools(require('../webpack/isomorphic').default)
  .development(process.env.NODE_ENV === 'development')
  .server(basePath, () => require('./server'));

```

**Comment by halt-hammerzeit** [comment]
This error is not related to this library.
Presumably you haven't set up babel loader in your webpack configuration.

**Comment by evgenosiptsov** [comment]
Ok, but how is server running via node include webpack configuraration? 
I do not understand webpack config including in server script.

I run this in node:
```
require('babel-register');

// Adds common/js to the app module path so we can access local modules without
// having to use relative paths on the server-side. This is done on the client
// side using webpack's `resolve`.
require('app-module-path').addPath('common/js');

// css-modules-require-hook package allows us to require css files on the server.
require('css-modules-require-hook')({
  extensions: ['.scss'],
  generateScopedName: require('../package.json').config.css,
  devMode: process.env.NODE_ENV === 'development'
});

// this must be equal to the Webpack configuration's "context" parameter
const basePath = require('path').resolve(__dirname, '..');
const ISOTools = require('webpack-isomorphic-tools');


global.__CLIENT__ = false;
global.__SERVER__ = true;
global.__DISABLE_SSR__ = false;  // <----- DISABLES SERVER SIDE RENDERING FOR ERROR DEBUGGING
global.__DEVELOPMENT__ = process.env.NODE_ENV !== 'production';


// this global variable will be used later in express middleware
global.ISOTools = new ISOTools(require('../webpack/isomorphic').default)
  .development(process.env.NODE_ENV === 'development')
  .server(basePath, () => require('./server'));

```

**Comment by halt-hammerzeit** [comment]
`webpack-isomorphic-tools` doesn't use webpack config.
It uses only `webpack-assets.json`.
`webpack-assets.json` is created by `webpack-isomorphic-tools/plugin`

**Comment by evgenosiptsov** [comment]
Ok, thanks. Sorry for obvious questions, If webpack-isomorphic-tools does not use webpack config, why webpack-isomorphic-tools trying to compile (and therefore show `unexptected token` error)?

**Comment by halt-hammerzeit** [comment]
Node.js tries to compile, not `webpack-isomorphic-tools`.
If it's not in the assets file, then it's compiled

**Comment by evgenosiptsov** [comment]
Ok, it's happend because express will run after `webpack-isomorphic-tools` execution. Ok. Suprising that i have `webpack-assets.json` file, proably this file incoreect and webpack create incorrectly  `webpack-assets.json` . Thank a lot! I am trying to find error.
