### ISSUE TITLE
Module did not self-register & webpack-assets.json for production is weird 

### ISSUE THREAD

**Issue by rolele** [halt-hammerzeit/webpack-isomorphic-tools#141]
Hi,
Thanks for this package, excellent work.
I facing some issues here, I am not sure if there are bugs or if I miss use the package.

I created a repo with source code and a Readme to explain the problem:
https://github.com/rolele/problem-webpack-isomorphic

I am using node v8.1.2

Basicaly:
## First problem + webpack isomorphic and hot reload not working (probably because of me doing something wrong).

At startup is ok.
I start editing `modules/EmptyWrapper/EmptyWrapper.scss` and save:
```
./~/css-loader?modules&localIdentName=[hash:base64:4]&importLoaders=1&sourceMap&camelCase=true!../~/postcss-loader/lib?{"sourceMap":true}!../~/sass-loader/lib/loader.js?{"sourceMap":true}!./theme/purecss.scss
Module build failed: Error: Module did not self-register.
```

Some shenanigans I am doing:
1)
`module/EmptyWrapper.js` require `theme/index.jss` which import my main scss: `theme/purecss.scss` which in turn importing all the scss:
```
@import '~purecss-sass/vendor/assets/stylesheets/_purecss.scss';
@import '../modules/PureBlog/PureBlog.scss';
@import '../modules/EmptyWrapper/EmptyWrapper.scss';
```
Having this global scss is very conveniant I think (those libs are very small).
2)
`ClassProps` component is just to speed up development.
This is a parent component that will change his children and dynamically change their classes to the js version of the style.
3)
The hot relad happen in `webpack.dev.server.js`. 
I start the compiler manually to bootstrap isomorphic tools in `bin/server.js`
I tried to follow the exmaple https://github.com/glenjamin/ultimate-hot-reloading-example on hot reload but I am not sure my setup is great yet.

## Second problem - assets.json for production is not really practical (maybe it was not intended to be used as such)

I want my server-side rendering to calculate the critical css and insert it in the page in addition of the <link> tag to the full css.

On dev `modules/Html.js`, `getAllStyles` will get the _style key from isomorphic assets props

On production (on the server) it is actually much more difficult to find all the styles when rendering the first page using Html.js:
```
const getAllStylesProd = assets =>
  Object
  .keys(assets)
  .map(key => assets[key])
  .filter(value => Array.isArray(value))
  .reduce((acc, array) => {
    acc += array[0][1];
    return acc;
  }, '');
```
Why does the structure of the assets has to change that much?
I am pretty sure this will breack as soon as I have more that 1 css right?

**Comment by halt-hammerzeit** [comment]
Hot reload is for client-side only.
It isn't related to server side (`webpack-isomorphic-tools`) in any way so it's your configuration.

As for the second part, it's not clear what you mean there.

**Comment by rolele** [comment]
So depending on the webpack config, if I run the plugin using:
`new WebpackToolsPlugin(webpackToolsConfig).development(true)` 
I will get a very different webpack.assets.json than if I run
`new WebpackToolsPlugin(webpackToolsConfig).development(false)`

Now on when I do server-side rendering my Html component try to use the assets prop provided by webpack-iso-tool package.
in my case the assets prop will look like that:
<img width="1082" alt="screen shot 2017-06-21 at 10 51 40 pm" src="https://user-images.githubusercontent.com/22406571/27384963-43095b9e-56d4-11e7-9366-e619749c91d7.png">

Object{
  loaders: [ [loaders, allcss, ""] ]
  scss_path: Object
}

**Comment by halt-hammerzeit** [comment]
The assets object maps from a path to a file contents.
In your case the first file seems to be an array for some reason.
That could mean that you'll need to debug your `parse` function for CSS assets to find out why is it outputting an array.
Perhaps some extra loader screws that up.
The built-in `parse` functions are for standard cases only, for custom cases a user is supposed to supply their own `parse` function.

**Comment by halt-hammerzeit** [comment]
Ah, I see, so your issue is the key.
Then it's the `path` function for the CSS asset type: use the right one.
https://github.com/halt-hammerzeit/webpack-isomorphic-tools#style-loader-css-stylesheets-with-css-modules-feature
Tweak in custom cases.

**Comment by rolele** [comment]
Thanks for the link, I will have a look.

Any chance I can get some help with my first issue?
I am not saying that the error is linked to server side rendering.
but the stack actually start from webpack iso tool just after editing a scss file:
```
ERROR in ./~/css-loader?modules&localIdentName=[hash:base64:4]&importLoaders=1&sourceMap&camelCase=true!./~/postcss-loader/lib?{"sourceMap":true}!./~/sass-loader/lib/loader.js?{"sourceMap":true}!./src/theme/purecss.scss
Module build failed: Error: Module did not self-register.
    at Object.Module._extensions..node (module.js:598:18)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at module.exports (/Users/others/problem-webpack-isomorphic/node_modules/node-sass/lib/binding.js:19:10)
    at Object.<anonymous> (/Users/others/problem-webpack-isomorphic/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:569:30)
    at Module._extensions..js (module.js:580:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/others/problem-webpack-isomorphic/node_modules/babel-register/lib/node.js:152:7)
```

**Comment by rolele** [comment]
sorry my bad it do not originate from webpack iso tool but yeah I am doing something wrong somewhere.
