### ISSUE TITLE
Error Since 2.2.0

### ISSUE THREAD

**Issue by dtothefp** [halt-hammerzeit/webpack-isomorphic-tools#16]
Just compiled package on Travis and after update to `2.2.0` I'm getting an error. As mentioned in some of my previous issues I'm using one webpack task to just compile my SCSS through webpack and extract text plugin. I'm also importing/requiring images in this bundle in order to generate stats on their hashed file paths and public path that I can use in my html templating. I use the `webpack-isomorpic-tools` plugin with this bundle just to generate stats because it is more convenient that making my own stats plugin that I was using previously. Since `2.2.0` I'm getting an error I don't understand?

here is my tools config:
```js
export default function({statsFile, isDev}) {
  return {
    debug: isDev,

    webpack_assets_file_path: statsFile,

    assets: {
      images: {
        extensions: [
          'jpeg',
          'jpg',
          'png',
          'gif'
        ],
        filter(m, regex, options, log) {
          return regex.test(m.name);
        },
        parser(m, options, log) {
          const {publicPath} = options.webpack_stats;
          const [fullName] = m.assets;

          return process.env.TRAVIS_BRANCH ? publicPath + path.sep + fullName : fullName;
        },
        naming(m, options, log) {
          const {name} = m;
          const base = path.basename(name, path.extname(name));
          return dashToCamel(base);
        }
      }
    }
  };
}
```

here are my loaders
```js
  const loaders = [
    {
      test: /\.jsx?$/,
      exclude: shouldExclude,
      loader: jsxLoader,
      query: isMainTask ? babelrc : babelQuery
    },
    {
      test: toolsPlugin.regular_expression('images'),
      loader: fileLoader
    }
]
```

here is the webpack file importing sass and images
```js
import '../scss/global.scss';

//require all the images
require.context('../img', true, /.(jpeg|jpg|png|gif)$/);

```

here is the terminal output
```sh
[13:45:06] Requiring external module babel-core/register
[13:45:08] Using gulpfile ~/dev/bdu/gulpfile.babel.js
[13:45:08] Starting 'build'...
[13:45:08] Starting 'clean'...
[13:45:08] Starting 'lint:test'...
[13:45:08] Starting 'lint:build'...
[13:45:08] Finished 'clean' after 277 ms
[13:45:09] Finished 'lint:test' after 711 ms
[13:45:10] Finished 'lint:build' after 1.81 s
[13:45:10] Starting 'lint'...
[13:45:10] Finished 'lint' after 5.57 μs
[13:45:10] Starting 'webpack:global'...
[13:45:10] Webpack Bundling global bundle
[13:45:10] Starting 'webpack:main'...
[13:45:10] Webpack Bundling main bundle
[13:45:10] Starting 'env'...
[13:45:10] Finished 'env' after 13 ms
[13:45:20] Webpack Bundled main bundle in 10006ms
[13:45:20] Finished 'webpack:main' after 10 s
webpack built c62c63e5e6cb5390d837 in 10006ms
==> 🚧  Webpack development server listening on port 8080
/Users/davidfox-powell/dev/bdu/src/src/img/donate-main.jpg.webpack-module:1
(function (exports, require, module, __filename, __dirname) { img/donate-main.jpg
                                                              ^

ReferenceError: img is not defined
    at Object.<anonymous> (/Users/davidfox-powell/dev/bdu/src/src/img/donate-main.jpg.webpack-module:1:63)
    at Module._compile (module.js:435:26)
    at Object._module3.default._extensions.(anonymous function) [as .webpack-module] (/Users/davidfox-powell/dev/bdu/node_modules/webpack-isomorphic-tools/node_modules/require-hacker/babel-transpiled-modules/require hacker.js:270:11)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at populate_assets (/Users/davidfox-powell/dev/bdu/node_modules/webpack-isomorphic-tools/babel-transpiled-modules/plugin/write assets.js:361:31)
    at Object.write_assets [as default] (/Users/davidfox-powell/dev/bdu/node_modules/webpack-isomorphic-tools/babel-transpiled-modules/plugin/write assets.js:64:2)
    at Compiler.<anonymous> (/Users/davidfox-powell/dev/bdu/node_modules/webpack-isomorphic-tools/babel-transpiled-modules/plugin/plugin.js:151:27)
    at Compiler.applyPlugins (/Users/davidfox-powell/dev/bdu/node_modules/webpack/node_modules/tapable/lib/Tapable.js:26:37)
    at Watching._done (/Users/davidfox-powell/dev/bdu/node_modules/webpack/lib/Compiler.js:78:17)
    at Watching.<anonymous> (/Users/davidfox-powell/dev/bdu/node_modules/webpack/lib/Compiler.js:61:18)
    at Compiler.emitRecords (/Users/davidfox-powell/dev/bdu/node_modules/webpack/lib/Compiler.js:282:37)
    at Watching.<anonymous> (/Users/davidfox-powell/dev/bdu/node_modules/webpack/lib/Compiler.js:58:19)
    at /Users/davidfox-powell/dev/bdu/node_modules/webpack/lib/Compiler.js:275:11

```

**Comment by halt-hammerzeit** [comment]
Try to update to the latest `webpack-isomorphic-tools` and then post you `debug` log

**Comment by dtothefp** [comment]
I see that in the above output the `src` directory is doubled up

```
at Object.<anonymous> (/Users/davidfox-powell/dev/bdu/src/src/img/donate-main.jpg.webpack-module:1:63)
```
but not sure why that is happening? I'll update and post debug info

**Comment by dtothefp** [comment]
debug log
```sh
[13:57:00] Requiring external module babel-core/register
[13:57:02] Using gulpfile ~/dev/bdu/gulpfile.babel.js
[13:57:02] Starting 'webpack:global'...
[13:57:02] Webpack Bundling global bundle
[webpack-isomorphic-tools/plugin] [debug] running write assets webpack plugin
[webpack-isomorphic-tools/plugin] [debug] getting javascript and styles for chunk "global"
[webpack-isomorphic-tools/plugin] [debug]  (got javascript)
[webpack-isomorphic-tools/plugin] [debug]  (got style)
[webpack-isomorphic-tools/plugin] [debug] No path parser specified for "images" assets. Using a default one.
[webpack-isomorphic-tools/plugin] [debug] parsing assets of type "images"
***FULLLNAME*** img/donate-main.jpg
[webpack-isomorphic-tools/plugin] [trace] Adding assset "./src/img/donate-main.jpg", module id 3 (in webpack-stats.debug.json)
***FULLLNAME*** img/favicon.png
[webpack-isomorphic-tools/plugin] [trace] Adding assset "./src/img/favicon.png", module id 4 (in webpack-stats.debug.json)
***FULLLNAME*** img/mark-h.png
[webpack-isomorphic-tools/plugin] [trace] Adding assset "./src/img/mark-h.png", module id 5 (in webpack-stats.debug.json)
[webpack-isomorphic-tools/plugin] [debug]  time taken: 1 ms
[require-hook] [debug] Hooking into *.webpack-module files loading
[webpack-isomorphic-tools/plugin] [debug] compiling assets
[require-hook] [debug] Loading source code for /Users/davidfox-powell/dev/bdu/src/src/img/donate-main.jpg.webpack-module
/Users/davidfox-powell/dev/bdu/src/src/img/donate-main.jpg.webpack-module:1
(function (exports, require, module, __filename, __dirname) { img/donate-main.jpg
                                                              ^

ReferenceError: img is not defined
    at Object.<anonymous> (/Users/davidfox-powell/dev/bdu/src/src/img/donate-main.jpg.webpack-module:1:63)
    at Module._compile (module.js:435:26)
    at Object._module3.default._extensions.(anonymous function) [as .webpack-module] (/Users/davidfox-powell/dev/bdu/node_modules/webpack-isomorphic-tools/node_modules/require-hacker/babel-transpiled-modules/require hacker.js:270:11)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at populate_assets (/Users/davidfox-powell/dev/bdu/node_modules/webpack-isomorphic-tools/babel-transpiled-modules/plugin/write assets.js:363:31)
    at Object.write_assets [as default] (/Users/davidfox-powell/dev/bdu/node_modules/webpack-isomorphic-tools/babel-transpiled-modules/plugin/write assets.js:64:2)
    at Compiler.<anonymous> (/Users/davidfox-powell/dev/bdu/node_modules/webpack-isomorphic-tools/babel-transpiled-modules/plugin/plugin.js:159:27)
    at Compiler.applyPlugins (/Users/davidfox-powell/dev/bdu/node_modules/webpack/node_modules/tapable/lib/Tapable.js:26:37)
    at Watching._done (/Users/davidfox-powell/dev/bdu/node_modules/webpack/lib/Compiler.js:78:17)
    at Watching.<anonymous> (/Users/davidfox-powell/dev/bdu/node_modules/webpack/lib/Compiler.js:61:18)
    at Compiler.emitRecords (/Users/davidfox-powell/dev/bdu/node_modules/webpack/lib/Compiler.js:282:37)
    at Watching.<anonymous> (/Users/davidfox-powell/dev/bdu/node_modules/webpack/lib/Compiler.js:58:19)
    at /Users/davidfox-powell/dev/bdu/node_modules/webpack/lib/Compiler.js:275:11
```

**Comment by halt-hammerzeit** [comment]
I have an idea, will release a new version soon

**Comment by dtothefp** [comment]
@halt-hammerzeit thanks, I'll constrain the version for now

**Comment by halt-hammerzeit** [comment]
Ok, try the new version
`npm install webpack-isomorphic-tools@latest --save`

**Comment by dtothefp** [comment]
@halt-hammerzeit awesome...that works. Is there an issue I should be aware of with my config or was it something internal?

**Comment by halt-hammerzeit** [comment]
It was internal: I added something like `'module.exports = "' + parsed + '"'` in case `parsed` is not a module source.

**Comment by dtothefp** [comment]
cool, thx for the help
