### ISSUE TITLE
Relative paths on require() call don't match the values in webpack-assets.json

### ISSUE THREAD

**Issue by sergesemashko** [halt-hammerzeit/webpack-isomorphic-tools#38]
Hi, 

I have quite unusual way of configuring webpack. We have multiple projects with similar architecture, so we are trying to reuse webpack configuration. 

I created an [example](https://github.com/sergesemashko/webpack-shared-configuration-example) of project structure we are using, webpack configuration is encapsulated [here](https://github.com/sergesemashko/webpack-tools), so you could reproduce the issues I'm having.

### 1st case

Path of required style doesn't match path in webpack-assets.json. Style is required from shared component which is in node_modules.

1. Open [http://localhost:3000/](http://localhost:3000/)
2. Error is thrown:
```bash
[1] [webpack-isomorphic-tools] [error] asset not found: ./~/react-shared-library-example/dist/components/MyStyledComponent.scss
[1] /Users/siarheisemashka/Sites/webpack-isomorphic-tools-example/node_modules/react-shared-library-example/dist/components/MyStyledComponent.js:29
[1]       { className: styles.wrapper },
[1]                          ^
[1] 
[1] TypeError: Cannot read property 'wrapper' of undefined
[1]     at MyStyledComponent.render (/Users/siarheisemashka/Sites/webpack-isomorphic-tools-example/node_modules/react-shared-library-example/dist/components/MyStyledComponent.js:29:26)
[1]     at [object Object].ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext (/Users/siarheisemashka/Sites/webpack-isomorphic-tools-example/node_modules/react/lib/ReactCompositeComponent.js:587:34)
[1]     at [object Object].ReactCompositeComponentMixin._renderValidatedComponent (/Users/siarheisemashka/Sites/webpack-isomorphic-tools-example/node_modules/react/lib/ReactCompositeComponent.js:607:32)
[1]     at [object Object].wrapper [as _renderValidatedComponent] (/Users/siarheisemashka/Sites/webpack-isomorphic-tools-example/node_modules/react/lib/ReactPerf.js:66:21)
[1]     at [object Object].ReactCompositeComponentMixin.mountComponent (/Users/siarheisemashka/Sites/webpack-isomorphic-tools-example/node_modules/react/lib/ReactCompositeComponent.js:220:30)
[1]     at [object Object].wrapper [as mountComponent] (/Users/siarheisemashka/Sites/webpack-isomorphic-tools-example/node_modules/react/lib/ReactPerf.js:66:21)
[1]     at Object.ReactReconciler.mountComponent (/Users/siarheisemashka/Sites/webpack-isomorphic-tools-example/node_modules/react/lib/ReactReconciler.js:37:35)
[1]     at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (/Users/siarheisemashka/Sites/webpack-isomorphic-tools-example/node_modules/react/lib/ReactMultiChild.js:241:44)
[1]     at ReactDOMComponent.Mixin._createContentMarkup (/Users/siarheisemashka/Sites/webpack-isomorphic-tools-example/node_modules/react/lib/ReactDOMComponent.js:591:32)
[1]     at ReactDOMComponent.Mixin.mountComponent (/Users/siarheisemashka/Sites/webpack-isomorphic-tools-example/node_modules/react/lib/ReactDOMComponent.js:479:29)
```

### 2nd case

`Webpack-assets.json` contains absolute path `/Users/siarheisemashka/Sites/webpack-isomorphic-tools-example/modules/components/About.scss`, but relative one `./modules/components/About.scss`  is required.

1. Open [http://localhost:3000/about](http://localhost:3000/about ) 
2. Error is thrown:
```bash
[1] [webpack-isomorphic-tools] [error] asset not found: ./modules/components/About.scss
[1] /Users/siarheisemashka/Sites/webpack-isomorphic-tools-example/modules/components/About.js:28
[1]       { className: styles.wrapper },
[1]                          ^
[1] 
[1] TypeError: Cannot read property 'wrapper' of undefined
[1]     at About.render (/Users/siarheisemashka/Sites/webpack-isomorphic-tools-example/modules/components/About.js:7:29)
[1]     at [object Object].ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext (/Users/siarheisemashka/Sites/webpack-isomorphic-tools-example/node_modules/react/lib/ReactCompositeComponent.js:587:34)
[1]     at [object Object].ReactCompositeComponentMixin._renderValidatedComponent (/Users/siarheisemashka/Sites/webpack-isomorphic-tools-example/node_modules/react/lib/ReactCompositeComponent.js:607:32)
[1]     at [object Object].wrapper [as _renderValidatedComponent] (/Users/siarheisemashka/Sites/webpack-isomorphic-tools-example/node_modules/react/lib/ReactPerf.js:66:21)
[1]     at [object Object].ReactCompositeComponentMixin.mountComponent (/Users/siarheisemashka/Sites/webpack-isomorphic-tools-example/node_modules/react/lib/ReactCompositeComponent.js:220:30)
[1]     at [object Object].wrapper [as mountComponent] (/Users/siarheisemashka/Sites/webpack-isomorphic-tools-example/node_modules/react/lib/ReactPerf.js:66:21)
[1]     at Object.ReactReconciler.mountComponent (/Users/siarheisemashka/Sites/webpack-isomorphic-tools-example/node_modules/react/lib/ReactReconciler.js:37:35)
[1]     at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (/Users/siarheisemashka/Sites/webpack-isomorphic-tools-example/node_modules/react/lib/ReactMultiChild.js:241:44)
[1]     at ReactDOMComponent.Mixin._createContentMarkup (/Users/siarheisemashka/Sites/webpack-isomorphic-tools-example/node_modules/react/lib/ReactDOMComponent.js:591:32)
[1]     at ReactDOMComponent.Mixin.mountComponent (/Users/siarheisemashka/Sites/webpack-isomorphic-tools-example/node_modules/react/lib/ReactDOMComponent.js:479:29)
```

**webpack-assets.json:**
```json
{
  "javascript": {
    "main": "http://localhost:3001/dist/main-8f70bcb9f4f52c2339c4.js"
  },
  "styles": {},
  "assets": {
    "../react-shared-library-example/dist/components/MyStyledComponent.scss": {
      "wrapper": "wrapper___398WI",
      "content": "content___2ECOw",
      "_style": ".wrapper___398WI {\n  width: 100%;\n  padding: 10px;\n}\n\n.wrapper___398WI .content___2ECOw {\n  width: 300px;\n  height: 60px;\n  margin: 0 auto;\n  background-color: #666;\n}\n"
    },
    "/Users/siarheisemashka/Sites/webpack-isomorphic-tools-example/modules/components/About.scss": {
      "wrapper": "wrapper___1Qxgf",
      "_style": ".wrapper___1Qxgf {\n  background-color: #222222;\n}\n"
    }
  }
}
```

Also, you can find webpack isomorphic tools config [here](https://github.com/sergesemashko/webpack-tools/blob/master/webpack/webpack-isomorphic-tools.js).

Most likely the roots of these issues are in encapsulated webpack config and I'm the only one who have them, but maybe changing paths in webpack-assets.json to absolute ones would help? Any thoughts on that?
 
Any help or advices would be highly appreciated.

**Comment by halt-hammerzeit** [comment]
Post your `webpack-stats.json` too.

**Comment by sergesemashko** [comment]
Here you go - [webpack-stats.json](https://gist.githubusercontent.com/sergesemashko/be9d0fe7be29c5ed373e/raw/f6acd3f14fdb59666e99740aa63260070ffdd573/webpack-stats.json)

**Comment by halt-hammerzeit** [comment]
I don't know why but for some reason in Webpack the name for that module is strange.

```
{
      "id": 284,
      "identifier": "/Users/siarheisemashka/Sites/webpack-isomorphic-tools-example/node_modules/react-shared-library-example/dist/components/MyStyledComponent.js",
      "name": "../react-shared-library-example/dist/components/MyStyledComponent.js",
      "index": 284,
```

It is in `node_modules` but at the same time it looks in a whole another folder.
Do you have any `npm link` magic installed or anything else.

You could also try running the project on a different machine (maybe your npm is messed up).
(I haven't tried running the project)

2nd. 

For some reason Webpack outputs an absolute path in the `module.name`

```
    {
      "id": 292,
      "identifier": "/Users/siarheisemashka/Sites/webpack-isomorphic-tools-example/node_modules/webpack-tools/node_modules/css-loader/index.js?modules&importLoaders=2&sourceMap&localIdentName=[local]___[hash:base64:5]!/Users/siarheisemashka/Sites/webpack-isomorphic-tools-example/node_modules/webpack-tools/node_modules/autoprefixer-loader/index.js?browsers=last 2 version!/Users/siarheisemashka/Sites/webpack-isomorphic-tools-example/node_modules/webpack-tools/node_modules/sass-loader/index.js?outputStyle=expanded&sourceMap!/Users/siarheisemashka/Sites/webpack-isomorphic-tools-example/modules/components/About.scss",
      "name": "./~/css-loader?modules&importLoaders=2&sourceMap&localIdentName=[local]___[hash:base64:5]!./~/autoprefixer-loader?browsers=last 2 version!./~/sass-loader?outputStyle=expanded&sourceMap!/Users/siarheisemashka/Sites/webpack-isomorphic-tools-example/modules/components/About.scss",
    }
```

Why is it using an absolute path there?
I don't know.
It should have used a relative path there.
Maybe it's somehow messed up.
I have no idea.

**Comment by sergesemashko** [comment]
Tried on another machine - the same error. All the dependencies are installed either from github or NPM, no `npm link` is used. Seems like the cause in webpack itself and executing it from `./node_modules/webpack-tools/`, `../react-shared-library-example/dist/components/MyStyledComponent.js` seems correct relatively to the current working directory when all the others paths are absolute.
 
I'll try to play with `style_modules: path` callback or execute webpack from the project folder.
Thanks anyway for giving the direction for debugging. Please, let me know if you have any other ideas.

**Comment by halt-hammerzeit** [comment]
Ok.
`webpack-isomorphic-tools` is based solely on `webpack-stats.json` (generated by Webpack itself) and `webpack-stats.json` is the only source of information it has.
If Webpack sometimes puts relative paths there and sometimes puts absolute paths in the same places then I don't know why does it do that.
Maybe someone who knows the inner workings of Webpack could answer that question.
My knowledge of Webpack is limited to some of its basic principles.

**Comment by sergesemashko** [comment]
:+1: thanks

**Comment by halt-hammerzeit** [comment]
About the wrong paths in `webpack-stats.json`
FYI
https://github.com/halt-hammerzeit/webpack-isomorphic-tools/issues/40

**Comment by sergesemashko** [comment]
updated to the latest version and the issue is gone, thanks

**Comment by BinahLinden** [comment]
I am using v2.2.26 and still seeing this issue on server render, relative css require is not getting mapped to assets absolute path.

**Comment by halt-hammerzeit** [comment]
@BinahLinden how about posting your `webpack-stats.json` and your debug log

**Comment by BinahLinden** [comment]
Thanks for responding. I did manage to get things straightened out. The issue seemed to be my directory organization, and the fact that my server requires that I have all components transpiled to ES2015, which I was doing with gulp, I was also using gulp to run webpack concurrently. I changed my order of operations to first gulp transpile code then run webpack via cli and all things are working. I do see ~250 lines of `modulename false` in my webpack-stats.json which I feel need to be addressed but at least things are serving as expected.

**Comment by halt-hammerzeit** [comment]
FYI
I'm posting this in every issue and PR to notify whoever may be interested:
today I've released an alternative helper library called [`universal-webpack`](https://github.com/halt-hammerzeit/universal-webpack).
It takes a different approach than `webpack-ismorphic-tools` and instead of hacking Node.js `require()` calls it just compiles all code with `target: 'node'` webpack configuration option.
As a result, all Webpack plugins and features are supported.
If you think you might need that here's an example project:
https://github.com/halt-hammerzeit/webpack-react-redux-isomorphic-render-example

**Comment by sergesemashko** [comment]
@halt-hammerzeit, thanks for notifying
